server.port=8080
spring.application.name=GestaoPessoas2026

# Configuração de serialização JSON
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss

# Log
logging.level.br.com.gestaopessoas2026=DEBUG
